[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200